-- Babytuna Inventory System - Seed Data
-- Run this after the initial schema migration

-- Insert Locations
INSERT INTO locations (id, name, short_code, active) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Babytuna Sushi', 'BTS', true),
  ('22222222-2222-2222-2222-222222222222', 'Babytuna Poki & Pho', 'BTP', true);

-- Insert Suppliers
INSERT INTO suppliers (name, phone, supplier_type, is_default) VALUES
  ('Ocean Fresh Seafood', '(555) 123-4567', 'fish_supplier', true),
  ('Pacific Rim Asian Market', '(555) 234-5678', 'asian_market', true),
  ('Sysco Food Service', '(555) 345-6789', 'main_distributor', true);

-- Insert Inventory Items (100+ items)

-- FISH CATEGORY (Fish Supplier) - 25 items
INSERT INTO inventory_items (name, category, supplier_category, base_unit, pack_unit, pack_size, active) VALUES
  -- Sushi-grade fish
  ('Ahi Tuna (Sushi Grade)', 'fish', 'fish_supplier', 'lb', 'case', 10, true),
  ('Atlantic Salmon (Sushi Grade)', 'fish', 'fish_supplier', 'lb', 'side', 4, true),
  ('Yellowtail Hamachi', 'fish', 'fish_supplier', 'lb', 'fillet', 2, true),
  ('Escolar (Super White Tuna)', 'fish', 'fish_supplier', 'lb', 'loin', 3, true),
  ('Albacore Tuna', 'fish', 'fish_supplier', 'lb', 'loin', 5, true),
  ('Unagi (Freshwater Eel)', 'fish', 'fish_supplier', 'piece', 'pack', 10, true),
  ('Tako (Octopus)', 'fish', 'fish_supplier', 'lb', 'piece', 3, true),
  ('Ika (Squid)', 'fish', 'fish_supplier', 'lb', 'pack', 5, true),
  ('Ebi (Cooked Shrimp)', 'fish', 'fish_supplier', 'piece', 'pack', 30, true),
  ('Amaebi (Sweet Shrimp)', 'fish', 'fish_supplier', 'piece', 'pack', 50, true),
  ('Hotate (Scallops)', 'fish', 'fish_supplier', 'piece', 'pack', 20, true),
  ('Kani (Crab Meat)', 'fish', 'fish_supplier', 'lb', 'container', 1, true),
  ('Tobiko (Flying Fish Roe)', 'fish', 'fish_supplier', 'oz', 'jar', 8, true),
  ('Masago (Capelin Roe)', 'fish', 'fish_supplier', 'oz', 'jar', 8, true),
  ('Ikura (Salmon Roe)', 'fish', 'fish_supplier', 'oz', 'jar', 8, true),
  ('Uni (Sea Urchin)', 'fish', 'fish_supplier', 'tray', 'case', 6, true),
  ('Saba (Mackerel)', 'fish', 'fish_supplier', 'piece', 'pack', 5, true),
  ('Smoked Salmon', 'fish', 'fish_supplier', 'lb', 'pack', 2, true),
  ('Salmon Belly', 'fish', 'fish_supplier', 'lb', 'pack', 3, true),
  ('Tuna Belly (Toro)', 'fish', 'fish_supplier', 'lb', 'piece', 2, true),
  ('Hirame (Flounder)', 'fish', 'fish_supplier', 'lb', 'fillet', 2, true),
  ('Tai (Red Snapper)', 'fish', 'fish_supplier', 'lb', 'fillet', 2, true),
  ('Hokkaido Scallops', 'fish', 'fish_supplier', 'piece', 'pack', 12, true),
  ('Snow Crab Legs', 'fish', 'fish_supplier', 'lb', 'case', 10, true),
  ('Soft Shell Crab', 'fish', 'fish_supplier', 'piece', 'case', 12, true),

-- PROTEIN CATEGORY (Main Distributor & Asian Market) - 15 items
  ('Ribeye Beef (Pho)', 'protein', 'main_distributor', 'lb', 'case', 20, true),
  ('Beef Brisket', 'protein', 'main_distributor', 'lb', 'piece', 8, true),
  ('Beef Meatballs', 'protein', 'asian_market', 'lb', 'bag', 5, true),
  ('Beef Tendon', 'protein', 'asian_market', 'lb', 'pack', 3, true),
  ('Beef Tripe', 'protein', 'asian_market', 'lb', 'pack', 3, true),
  ('Pork Belly', 'protein', 'main_distributor', 'lb', 'slab', 10, true),
  ('Char Siu Pork', 'protein', 'asian_market', 'lb', 'piece', 3, true),
  ('Ground Pork', 'protein', 'main_distributor', 'lb', 'pack', 5, true),
  ('Chicken Breast', 'protein', 'main_distributor', 'lb', 'case', 40, true),
  ('Chicken Thigh', 'protein', 'main_distributor', 'lb', 'case', 40, true),
  ('Firm Tofu', 'protein', 'asian_market', 'block', 'case', 12, true),
  ('Silken Tofu', 'protein', 'asian_market', 'block', 'case', 12, true),
  ('Fried Tofu Puffs', 'protein', 'asian_market', 'piece', 'bag', 50, true),
  ('Tempeh', 'protein', 'asian_market', 'block', 'pack', 4, true),
  ('Imitation Crab Stick', 'protein', 'main_distributor', 'stick', 'pack', 30, true),

-- PRODUCE CATEGORY - 25 items
  ('Cucumber (Japanese)', 'produce', 'main_distributor', 'piece', 'case', 24, true),
  ('Avocado (Hass)', 'produce', 'main_distributor', 'piece', 'case', 48, true),
  ('Green Onion', 'produce', 'main_distributor', 'bunch', 'case', 24, true),
  ('Carrot', 'produce', 'main_distributor', 'lb', 'bag', 25, true),
  ('Bean Sprouts', 'produce', 'asian_market', 'lb', 'bag', 5, true),
  ('Jalapeño Pepper', 'produce', 'main_distributor', 'lb', 'case', 10, true),
  ('Serrano Pepper', 'produce', 'main_distributor', 'lb', 'case', 5, true),
  ('Cilantro', 'produce', 'main_distributor', 'bunch', 'case', 30, true),
  ('Thai Basil', 'produce', 'asian_market', 'bunch', 'case', 12, true),
  ('Mint', 'produce', 'main_distributor', 'bunch', 'case', 12, true),
  ('Romaine Lettuce', 'produce', 'main_distributor', 'head', 'case', 24, true),
  ('Iceberg Lettuce', 'produce', 'main_distributor', 'head', 'case', 24, true),
  ('Fresh Ginger', 'produce', 'asian_market', 'lb', 'case', 10, true),
  ('Garlic', 'produce', 'main_distributor', 'lb', 'case', 30, true),
  ('Yellow Onion', 'produce', 'main_distributor', 'lb', 'bag', 50, true),
  ('Red Onion', 'produce', 'main_distributor', 'lb', 'bag', 25, true),
  ('Lime', 'produce', 'main_distributor', 'piece', 'case', 200, true),
  ('Lemon', 'produce', 'main_distributor', 'piece', 'case', 165, true),
  ('Bok Choy', 'produce', 'asian_market', 'lb', 'case', 20, true),
  ('Napa Cabbage', 'produce', 'asian_market', 'head', 'case', 8, true),
  ('Daikon Radish', 'produce', 'asian_market', 'piece', 'case', 12, true),
  ('Shiso Leaf (Perilla)', 'produce', 'asian_market', 'pack', 'case', 10, true),
  ('Edamame (Fresh)', 'produce', 'asian_market', 'lb', 'bag', 5, true),
  ('Mango', 'produce', 'main_distributor', 'piece', 'case', 12, true),
  ('Pickled Ginger (Gari)', 'produce', 'asian_market', 'lb', 'jar', 5, true),

-- DRY GOODS CATEGORY - 20 items
  ('Sushi Rice (Calrose)', 'dry', 'asian_market', 'lb', 'bag', 50, true),
  ('Jasmine Rice', 'dry', 'asian_market', 'lb', 'bag', 50, true),
  ('Nori Sheets (Full)', 'dry', 'asian_market', 'sheet', 'pack', 100, true),
  ('Nori Sheets (Half)', 'dry', 'asian_market', 'sheet', 'pack', 100, true),
  ('Panko Breadcrumbs', 'dry', 'asian_market', 'lb', 'bag', 5, true),
  ('Tempura Batter Mix', 'dry', 'asian_market', 'lb', 'bag', 5, true),
  ('Sesame Seeds (White)', 'dry', 'asian_market', 'lb', 'bag', 5, true),
  ('Sesame Seeds (Black)', 'dry', 'asian_market', 'lb', 'bag', 5, true),
  ('Rice Vinegar', 'dry', 'asian_market', 'gal', 'case', 4, true),
  ('Pho Noodles (Dry)', 'dry', 'asian_market', 'lb', 'case', 25, true),
  ('Pho Noodles (Fresh)', 'dry', 'asian_market', 'lb', 'case', 10, true),
  ('Ramen Noodles', 'dry', 'asian_market', 'portion', 'case', 40, true),
  ('Udon Noodles', 'dry', 'asian_market', 'portion', 'case', 30, true),
  ('Rice Paper (Spring Roll)', 'dry', 'asian_market', 'sheet', 'pack', 100, true),
  ('Wonton Wrappers', 'dry', 'asian_market', 'pack', 'case', 24, true),
  ('Furikake Seasoning', 'dry', 'asian_market', 'oz', 'jar', 8, true),
  ('Bonito Flakes', 'dry', 'asian_market', 'oz', 'bag', 16, true),
  ('Dried Shiitake Mushrooms', 'dry', 'asian_market', 'oz', 'bag', 16, true),
  ('Kombu (Kelp)', 'dry', 'asian_market', 'oz', 'pack', 8, true),
  ('Tapioca Pearls', 'dry', 'asian_market', 'lb', 'bag', 5, true),

-- DAIRY & COLD CATEGORY - 10 items
  ('Cream Cheese', 'dairy_cold', 'main_distributor', 'lb', 'case', 30, true),
  ('Mayonnaise', 'dairy_cold', 'main_distributor', 'gal', 'case', 4, true),
  ('Eggs (Large)', 'dairy_cold', 'main_distributor', 'dozen', 'case', 15, true),
  ('Unsalted Butter', 'dairy_cold', 'main_distributor', 'lb', 'case', 36, true),
  ('Heavy Cream', 'dairy_cold', 'main_distributor', 'qt', 'case', 12, true),
  ('Miso Paste (White)', 'dairy_cold', 'asian_market', 'lb', 'tub', 2, true),
  ('Miso Paste (Red)', 'dairy_cold', 'asian_market', 'lb', 'tub', 2, true),
  ('Kimchi', 'dairy_cold', 'asian_market', 'lb', 'jar', 5, true),
  ('Spicy Mayo Base', 'dairy_cold', 'main_distributor', 'gal', 'jug', 1, true),
  ('Wasabi Paste', 'dairy_cold', 'asian_market', 'lb', 'tube', 1, true),

-- FROZEN CATEGORY - 10 items
  ('Edamame (Frozen)', 'frozen', 'asian_market', 'lb', 'bag', 5, true),
  ('Gyoza (Pork)', 'frozen', 'asian_market', 'piece', 'bag', 50, true),
  ('Gyoza (Vegetable)', 'frozen', 'asian_market', 'piece', 'bag', 50, true),
  ('Tempura Shrimp', 'frozen', 'asian_market', 'piece', 'box', 30, true),
  ('Pho Broth Base', 'frozen', 'asian_market', 'qt', 'case', 8, true),
  ('Beef Bones (Pho)', 'frozen', 'asian_market', 'lb', 'case', 40, true),
  ('Chicken Stock', 'frozen', 'main_distributor', 'gal', 'case', 4, true),
  ('Mochi Ice Cream', 'frozen', 'asian_market', 'piece', 'box', 24, true),
  ('Spring Roll (Frozen)', 'frozen', 'asian_market', 'piece', 'case', 100, true),
  ('Taro Root (Frozen)', 'frozen', 'asian_market', 'lb', 'bag', 5, true),

-- SAUCES CATEGORY - 15 items
  ('Soy Sauce', 'sauces', 'asian_market', 'gal', 'case', 4, true),
  ('Low Sodium Soy Sauce', 'sauces', 'asian_market', 'gal', 'case', 4, true),
  ('Ponzu Sauce', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Eel Sauce (Unagi)', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Sriracha', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Hoisin Sauce', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Fish Sauce', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Oyster Sauce', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Sesame Oil', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Chili Oil', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Teriyaki Sauce', 'sauces', 'asian_market', 'gal', 'jug', 1, true),
  ('Sweet Chili Sauce', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Sambal Oelek', 'sauces', 'asian_market', 'jar', 'case', 12, true),
  ('Rice Wine (Mirin)', 'sauces', 'asian_market', 'bottle', 'case', 12, true),
  ('Sake (Cooking)', 'sauces', 'asian_market', 'bottle', 'case', 12, true),

-- PACKAGING CATEGORY - 12 items
  ('Takeout Container (Small)', 'packaging', 'main_distributor', 'piece', 'case', 250, true),
  ('Takeout Container (Medium)', 'packaging', 'main_distributor', 'piece', 'case', 200, true),
  ('Takeout Container (Large)', 'packaging', 'main_distributor', 'piece', 'case', 150, true),
  ('Pho Bowl (32oz)', 'packaging', 'main_distributor', 'piece', 'case', 200, true),
  ('Sushi Tray (Black)', 'packaging', 'main_distributor', 'piece', 'case', 200, true),
  ('Chopsticks (Disposable)', 'packaging', 'asian_market', 'pair', 'case', 1000, true),
  ('Soy Sauce Packets', 'packaging', 'asian_market', 'packet', 'case', 500, true),
  ('Wasabi Packets', 'packaging', 'asian_market', 'packet', 'case', 500, true),
  ('Ginger Packets', 'packaging', 'asian_market', 'packet', 'case', 500, true),
  ('Paper Napkins', 'packaging', 'main_distributor', 'piece', 'case', 6000, true),
  ('Plastic Spoons', 'packaging', 'main_distributor', 'piece', 'case', 1000, true),
  ('To-Go Bags (Large)', 'packaging', 'main_distributor', 'piece', 'case', 500, true);
