-- Phase 2b: manager-issued, single-use invite links.
-- Tokens are opaque, URL-safe values generated by the create-invite edge function.

create extension if not exists "pgcrypto";

create table if not exists public.invites (
  id uuid primary key default gen_random_uuid(),
  token text not null unique
    check (token ~ '^[A-Za-z0-9_-]{22,}$'),
  invited_name text not null,
  role text not null check (role in ('employee', 'manager')),
  module_preset jsonb not null default '{}'::jsonb,
  expires_at timestamptz not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  used_at timestamptz,
  used_by uuid references auth.users(id),
  revoked_at timestamptz,
  check ((used_at is null) = (used_by is null))
);

alter table public.invites enable row level security;

-- Managers may manage invite records in the dashboard. Anonymous callers have
-- no direct table access; public validation and acceptance stay in edge functions.
revoke all on table public.invites from anon, authenticated;
grant select, insert, update, delete on table public.invites to authenticated;

create policy invites_manager_all
  on public.invites
  for all to authenticated
  using (public.current_user_is_manager())
  with check (public.current_user_is_manager());
